[build-system]
requires = ["setuptools>=61.0", "wheel", "pyinstaller"]
build-backend = "setuptools.build_meta"

[tool.pyinstaller]
console_scripts = ["deprotocol = deprotocol.app.main:main"]

[tool.distutils.bdist_wheel]
universal = true
