name: Build Dechat

on: [push]

jobs:
  setup-dependencies:
    runs-on: ubuntu-latest
    name: Setup dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install coverage
          pip install -r requirements.txt

  build-wheel:
    runs-on: ubuntu-latest
    name: Build Wheel
    steps:
    - name: Build wheel
      run: |
        python -m build . --wheel

  wheel-test:
    runs-on: ubuntu-latest
    name: Test built package
    steps:
      - name: Install built package
        run: |
          python -m pip install dist/*.whl
          pip install build
      - name: Execute tests based on build
        run: |
          pytest

  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Run tests
        run: |
          coverage run --source=src -m pytest

  generate-coverage-report:
    runs-on: ubuntu-latest
    name: Coverage reporter
    steps:
      - name: Generate coverage report
        run: |
          coverage xml

  upload-coverage-report:
    runs-on: ubuntu-latest
    name: Coverage reporter
    steps:
      - name: Upload coverage report
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml