name: Build Dechat

on: [push]


jobs:
  setup-python:
    runs-on: ubuntu-latest
    name: Setup python
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

  build-wheel:
    runs-on: ubuntu-latest
    name: Build Wheel
    needs: setup-python
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build wheel
        run: |
          python -m build . --wheel

  wheel-test:
    runs-on: ubuntu-latest
    name: Test built package
    needs: [setup-python, build-wheel]
    steps:
      - name: Install built package
        run: |
          python -m pip install dist/*.whl
          pip install build
      - name: Execute tests based on build
        run: |
          pytest

  test:
    runs-on: ubuntu-latest
    name: Run tests
    needs: setup-python
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install -r requirements.txt
      - name: Run tests
        run: |
          coverage run --source=src -m pytest

  generate-coverage-report:
    runs-on: ubuntu-latest
    name: Coverage reporter
    needs: test
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
      - name: Generate coverage report
        run: |
          coverage xml

  upload-coverage-report:
    runs-on: ubuntu-latest
    name: Coverage reporter
    needs: generate-coverage-report
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
      - name: Upload coverage report
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml