name: Build Dechat

on: [push]


jobs:
  setup-python:
    runs-on: ubuntu-latest
    name: Setup python
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

  build-wheel:
    runs-on: ubuntu-latest
    name: Build Wheel
    needs: setup-python
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build wheel
        run: |
          python -m build . --wheel
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: dist/*.whl

  wheel-test:
    runs-on: ubuntu-latest
    name: Test built package
    needs: build-wheel
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: wheel
          path: deprotocol.whl
      - name: Install built package
        run: |
          python -m pip install ./deprotocol.whl
          pip install build
      - name: Execute tests based on build
        run: |
          pytest

  test:
    runs-on: ubuntu-latest
    name: Run tests
    needs: setup-python
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install pytest
          pip install -r requirements.txt
      - name: Run tests
        run: |
          coverage run --source=src -m pytest
          coverage report

  generate-coverage-report:
    runs-on: ubuntu-latest
    name: Generate coverage report
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install pytest
          pip install -r requirements.txt
      - name: Generate coverage report
        run: |
          coverage run --source=src -m pytest
          coverage xml
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.xml

  upload-coverage-report:
    runs-on: ubuntu-latest
    name: Upload coverage report
    needs: generate-coverage-report
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: coverage
          path: coverage.xml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
      - name: Upload coverage report
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage.xml